license="MIT License https://github.com/bl4ckscor3/SuspiciousZombification/blob/26.1/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/SuspiciousZombification/issues"

[[mods]]
	modId="suszombification"
	version="${file.jarVersion}"
	displayName="Suspicious Zombification"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/suspicious-zombification"
	authors="Redstone_Dubstep, bl4ckscor3"
	description='''A mod about zombifying animals, fighting off the zombies' curse, eating suspicious pies, and benefiting from their effects.'''

[[mixins]]
    config="suszombification.mixins.json"

[[dependencies.suszombification]]
	modId="neoforge"
	type="required"
	versionRange="[26,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.suszombification]]
	modId="minecraft"
	type="required"
	versionRange="[26,)"
	ordering="NONE"
	side="BOTH"
